### ISSUE TITLE
Liscense Key???

### ISSUE THREAD

**Issue by ApplePieCodes** [CrystalOSDevelopment/CrystalOS_Alpha#3]
Where do I obtain a license key. None of my friends have one and you don't list an email/discord/any form of contact. If you do not provide license keys, I don't think you should claim the OS to be OSS, as it cannot be tested in development without direct contact.

**Comment by CrystalOSDevelopment** [comment]
Hello there! Sorry for the late reply. I see you were unable to find the licence key and for that, I'm really sorry. The experience you had is unforgivable on my part, so without wasting your precious time any further, here's your product key that you've been so eager to obtain:
S57U-GS68-ARK0-A230
I hope you'll have a better experience next time!
Ps.: The key was literally mentioned and also made public one issue ago. So take a gander to issue #2 if you will and have any more free time after reading this.
Have a nice day!
__ initdeveloper __ (Discord, but without spaces)

**Comment by ApplePieCodes** [comment]
> Hello there! Sorry for the late reply. I see you were unable to find the licence key and for that, I'm really sorry. The experience you had is unforgivable on my part, so without wasting your precious time any further, here's your product key that you've been so eager to obtain: S57U-GS68-ARK0-A230 I hope you'll have a better experience next time! Ps.: The key was literally mentioned and also made public one issue ago. So take a gander to issue #2 if you will and have any more free time after reading this. Have a nice day! __ initdeveloper __ (Discord, but without spaces)

thank you. you should probably put a notice in the readme since most people probably wont look in PRs for that.
